### ISSUE TITLE
Create 'default' script group when initialising the database

### ISSUE THREAD

**Issue by mfitzp** [wooey/django-djangui#10]
Adding scripts requires a script group to be created. It would be nice to have a 'default' script group created to simplify setup.

**Comment by Chris7** [comment]
I agree, scripts added from the command line already do this. I don't know how hackish this would be considered, but we could use a lambda function to have a default object created for script group. Something like:

script_group = models.ForeignKey(...default=lambda x: ScriptGroups.objects.get_or_create(DEFAULT_NAME)[0])

Or we could just handle it in the save code and add blank=True to our model to avoid form validation issues.

**Comment by mfitzp** [comment]
Can we use [fixtures](https://docs.djangoproject.com/en/1.8/howto/initial-data/) for this? I'm a little rusty on Django but I remember pre-populating tables like that before. On the `script_group` field it should automatically select the first in the list if there is one there.

**Comment by Chris7** [comment]
The issue with fixtures is they would be orm dependent. I think handling it in the script save method is the best approach, since it will automatically create a group if it doesn't exist. I think all we need to do is add blank=True for this to be added.

**Comment by Chris7** [comment]
The documentation disagrees with me on that statement, but I've had problems importing fixtures from a postgresql db to sqlite3. Another reason I'd say do it in the model is so it's easier to add djangui to a project. There wouldn't be a loaddata step.

**Comment by mfitzp** [comment]
Sure I'm good with that. The documentation I pointed seems to suggest not using them in combination with migrations and doing a data migration instead. I don't know if that is any better?

If the lambda approach works I'm all for it :+1:

**Comment by mfitzp** [comment]
Since we're on the subject: what do you see the purpose of script groups to be (thinking from the UI perspective) are they to group similar scripts, or is it something else?

I'm working on the script page listing at the moment and will be adding filtering (e.g. type search text to filter available scripts). Grouping by group doesn't make sense in that context (search should return best-first). What do you think of tagging as an alternative to grouping?

**Comment by Chris7** [comment]
The purpose of a script group was to group similar scripts together. 

However, some scripts can be grouped in a variety of ways and script groups doesn't really allow that. I think tagging is a great way to reflect this, and can maintain the existing grouping capability (ui group by tag mode). 

So I'm for it. What sort of default interface are you envisioning for the user to navigate?

**Comment by Chris7** [comment]
I omitted one detail as well, ScriptGroup held permissions as well. So access could be set at the script group level, the script level, or both. Tags wouldn't have this same capability since that is a classifier scheme. 

Another missing aspect is the group order, which I liked to be able to prioritize things on your dashboard. However, I think we can make a better version though for users where they can favorite/re-organize scripts to customize their groups/displays so the ordering isn't a real issue to me since it's a UI flaw that just the admin organizes things :). 

I like the group level access control because it's a very simple way to control a lot with little effort, but I think the flexibility tags offer outweigh that laziness. Do you have any ideas on how this could control access to groups of scripts?

**Comment by mfitzp** [comment]
I think sticking with the script groups for access control is sensible. The ordering, grouping of display etc. is a different thing and can be handled with tags/categories. I can imagine for example scripts with high processing requirements might want to be 'grouped' together or scripts for 'internal' and 'external' users.

We might want to extend this later, but we should probably wait to see real use cases for that.

I'll look into tagging for organising and filtering scripts. We probably want to add some search capability too for larger sites (django-haystack is good for this in my experience). We might want to offer these things as optional bolt-ons and degrade gracefully to avoid Wooey ending up with 500 dependencies though :)

**Comment by mfitzp** [comment]
@Chris7 Is this working (the default script group)?

**Comment by Chris7** [comment]
Implemented here: https://github.com/wooey/django-djangui/pull/29

**Comment by mfitzp** [comment]
Closed by #29
