### ISSUE TITLE
Can't GET file output using wooey with an existing django project

### ISSUE THREAD

**Issue by brian-bk** [wooey/django-djangui#12]
Hello, I'm having a problem where django cannot find an output file that was created by wooey. I'm using wooey 0.2.6.

I added wooey along with an existing django project. In `urls.py` I have the url: 
`url(r'^wooey/', include('wooey.urls'))`.
But after a job is submitted and I try to view an output file I receive a django 404 page. The request url is as follows:
`http://10.xx.xx.xx:xxxx/wooey/celery/24/wooey_files/brian/djanguifront/24/salt.log`
where salt.log is my file I'm trying to get.
The patterns that django look for include:

```
^wooey/ ^ ^celery/command$ [name='celery_task_command']
^wooey/ ^ ^celery/status$ [name='celery_results']
^wooey/ ^ ^celery/(?P<job_id>[a-zA-Z0-9\-]+)/$ [name='celery_results_info']
^wooey/ ^ ^djscript/...
```

...And no more with the `wooey/celery` precursor.
I reach the 404 url from first being located at this job page:
`http://10.xx.xx.xx:xxxx/wooey/celery/24/#`

Now the `salt.log` file is created because it is in my django project (`mysite`) in this location:
`mysite/wooey_files/brian/djanguifront/24/salt.log`

I tried this out with a wooey-only project and it worked. Its request url was:
`http://10.xx.xx.xx:xxxx/uploads/wooey_files/brian/djanguifront/3/salt.log`
The file location is different for the created django project (`wooproj`):
`wooproj/wooproj/user_uploads/wooey_files/brian/djanguifront/3/salt.log`

So for some reason the url is not being matched. Now the file itself is not created by the script `djanguifront.py` but `djanguifront.py` imports a different script that creates this file. I'm not sure if this has anything to do with it since it works for a wooey-only project. The directory structure is also different between the two, the wooey-only contains at the django base: `$DJ/wooproj/user_uploads/wooey_files` where the django project contained at it's base: `$DJ/wooey_files`.

For reference here is a list of all of the wooey urls that django looks for:

```
^wooey/ ^ ^celery/command$ [name='celery_task_command']
^wooey/ ^ ^celery/status$ [name='celery_results']
^wooey/ ^ ^celery/(?P<job_id>[a-zA-Z0-9\-]+)/$ [name='celery_results_info']
^wooey/ ^ ^djscript/(?P<script_group>[a-zA-Z0-9\-\_]+)/(?P<script_name>[a-zA-Z0-9\-\_]+)/(?P<job_id>[a-zA-Z0-9\-]+)$ [name='wooey_script_clone']
^wooey/ ^ ^djscript/(?P<script_group>[a-zA-Z0-9\-\_]+)/(?P<script_name>[a-zA-Z0-9\-\_]+)/$ [name='wooey_script']
^wooey/ ^ ^profile/$ [name='profile_home']
^wooey/ ^ ^$ [name='wooey_home']
^wooey/ ^ ^$ [name='wooey_task_launcher']
^wooey/ ^ ^accounts/login/ [name='wooey_login']
^wooey/ ^ ^accounts/register/ [name='wooey_register']
^wooey/ ^ ^login/$ [name='login']
^wooey/ ^ ^logout/$ [name='logout']
^wooey/ ^ ^password_change/$ [name='password_change']
^wooey/ ^ ^password_change/done/$ [name='password_change_done']
^wooey/ ^ ^password_reset/$ [name='password_reset']
^wooey/ ^ ^password_reset/done/$ [name='password_reset_done']
^wooey/ ^ ^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='password_reset_confirm']
^wooey/ ^ ^reset/done/$ [name='password_reset_complete']
```

**Comment by Chris7** [comment]
Hey @brian-kl, I'm a bit confused. Can you clear a few things up so I can assess it:

1) Are you using this branch of django-djangui? By saying you are using Wooey 0.2.6, I'm confused because the code here is not available on pypi, as it needs to be installed directly via pip/git.

2) Does your Django project serve files? If you added to an existing project and Django is not setup to serve files, it will fail. You either need to use a service like ngix/apache/etc. for serving static files, or you can setup it in Django by adding this to your urls (note all the caveats to serving with Django apply):

```
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
```

3) Can I see your settings file (you can scrub your keys/etc out). It may be an issue with your MEDIA_ROOT and if it's a wooey bug, I'd love to iron it out.

**Comment by brian-bk** [comment]
Yes I got wooey with pip install wooey. Ah did not realize I have to add MEDIA_ROOT. Here is a copy of my whole settings.py, with wooey-specific settings at the bottom.

```
#WOOEY
import djcelery
djcelery.setup_loader()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []
# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appsinfo',
    'wooey',
    'djcelery',
    'kombu.transport.django',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/var/ssadmin/djcode/mysite/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'appdb',
        'USER': 'appuser',
        'PASSWORD': 'burgerking',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'US/Eastern'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# WOOEY CUSTOM
#user_settings
WOOEY_ALLOW_ANONYMOUS = True

CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'
BROKER_URL = 'django://'
CELERY_TRACK_STARTED = True
WOOEY_CELERY = True
CELERY_SEND_EVENTS = True

AUTHENTICATION_BACKEND = 'django.contrib.auth.backends.ModelBackend'
#MIDDLEWARE_CLASSES = list(MIDDLEWARE_CLASSES)
#MIDDLEWARE_CLASSES.append('mysite.middleware.ProcessExceptionMiddleware')

WOOEY_CELERY_APP_NAME = 'wooey.celery'
WOOEY_CELERY_TASKS = 'wooey.tasks'
# END WOOEY CUSTOM
```

**Comment by Chris7** [comment]
Thanks for those details.

First, you can't use pip install wooey for this. The wooey installed by pip is run on flask. I sort of have no idea how it works at all for you right now.

You can install this repo with:

pip install git+https://github.com/wooey/django-djangui.git

However, note that it is subject to change. If you want to be a guinea pig here, you are more than welcome to :). Though I will admit the master is fairly stable so you should be ok.

If you have a django project and don't want to use git to install, you can look at the main branch of this project, https://github.com/Chris7/django-djangui, which you can install by pip install django-djangui. That is what this is based off of. We're combining wooey with django-djangui (keeping django and most of the core of djangui)

If you continue and install either this, I'd like to know if it integrates with your existing project. I think a MEDIA_ROOT isn't necessary, but would be a good thing to setup to control where user uploads end up.

**Comment by brian-bk** [comment]
O yes sorry I did forget, I compiled from source from the git Makefile, it wasn't directly by pip and have the requirements satisfied for the pip install of wooey/django-djangui. I'll try to get the MEDIA files situated now, I'll let you know how it goes.

**Comment by brian-bk** [comment]
Ah got it to work! I had to define my own MEDIA_ROOT/URL and STATIC_ROOT/URLs in the settings.py file, and added the static urls you mentioned to the urls.py. Thanks so much for your help and speedy replies haha.

**Comment by Chris7** [comment]
Thanks @brian-bk. It's important for these things to appear in the readme/install instructions. Thank you for your patience and feedback as well! We're planning a lot of new things, so feel free to suggest new features/etc. and look at our issues/pull requests to see what we have in store for the official release.
