### ISSUE TITLE
Combine same-type same-filename outputs

### ISSUE THREAD

**Issue by mfitzp** [wooey/django-djangui#15]
Working on the new layout it occurs that sometimes scripts may output alternate types for the same file. The obvious example would be a script generating figures which might output both `.png` and `.svg` versions of the same plot. 

I think it would be nice if a file of the same _sort_ (e.g. image) is available with the same filename but different extension to group these together in a single visual item int the interface (with an precendence order determining which is displayed). 

We could support toggling between the alternatives but the main thought would be to provide a download drop down that lists the two formats ("Download as .png" etc.)

**Comment by Chris7** [comment]
:+1: 

I'm for it. I would like to revisit the file detection and grouper though to see if we could make it more dynamic to user's needs. The idea is more like an admin interface to customize what is detected and add new detection routines (just simple regex stuff). We fetch these entries on app loading to avoid hitting the database everytime a file is checked.

**Comment by mfitzp** [comment]
Moving to the Wooey repo.
