### ISSUE TITLE
The Merge

### ISSUE THREAD

**Issue by mfitzp** [wooey/django-djangui#17]
The update to the interface is coming along nicely and I expect to have it complete within the week. Once that's merged into `master` here we should probably look at creating a list of minimal issues/fixes that need to be applied before merging over into the `Wooey` repo. It doesn't need to get up to a 1.0 state, just be "working". 

There are a few issues on this repo that would probably make sense to move over to the post-merge - mostly things that are marked as enhancement?

**Comment by Chris7** [comment]
Sounds good. I made a milestone of 'Wooey Release', we can make a new tag 'Wooey Merge' to mark things to be completed.

**Comment by Chris7** [comment]
Here's an idea -- things for post merge we post on Wooey's tracker and things for the merge itself are kept here.

**Comment by mfitzp** [comment]
Yep, sounds good.

**Comment by mfitzp** [comment]
@Chris7 I've run a test merge on top of a forked repo here: https://github.com/mfitzp/Wooey
It appears to have worked, preserving all history. In the real run it won't be possible to do it on a fork, but instead to the main repo (it requires a force-push over the top because of the history rewrite).

The commands are here (mostly based off http://jasonkarns.com/blog/merge-two-git-repositories-into-one/)

```
git clone https://github.com/mfitzp/Wooey wooey-merge-test
cd wooey-merge-test/

# Move all the flask files into a separate folder
mkdir flask
git mv [!f]* flask
git commit -a -m "Merging djangui-wooey"

# Rewrite the history so flask files always were under /flask
git filter-branch --index-filter     'git ls-files -s | sed "s-\t-&flask/-" |
     GIT_INDEX_FILE=$GIT_INDEX_FILE.new \
     git update-index --index-info &&
     mv $GIT_INDEX_FILE.new $GIT_INDEX_FILE' HEAD

# Add the django remote and merge it into the current branch
git remote add -f djangui https://github.com/wooey/django-djangui.git
git merge -s ours --no-commit djangui/master
git read-tree --prefix=django -u djangui/master

# Move the django code up into the root folder
git mv * ..
git mv ./.* ..
git commit -m "Merged djangui"
```

**Comment by Chris7** [comment]
@mfitzp -- Looks good to me. Awesome work!

**Comment by mfitzp** [comment]
@Chris7 Getting a few emails about "which repo should I be using" and wondering if it's maybe time to go ahead with the merge and clear things up. The outstanding issues can be moved across.

I'm going to add a slightly hacky fix to make the sidebar "remember" search for the time being - the longer goal would probably be to switch to a js/JSON backend for most of the UI (with either angular.js or ember.js as a framework) so all this is dynamic.

**Comment by Chris7** [comment]
@mfitzp Ok, I'll fix clinto's api today so we don't have compatibility issues soon as we release.

For remembering searches -- can you be more specific? Do you mean a dropdown of things the user commonly searches for?

**Comment by mfitzp** [comment]
Sorry... vagueness. I meant that you search in the sidebar, then click to open a script. The problem is that currently the page reloads and so wipes the search. I'd put an auto-requery in there to pre-fill it but since the sidebar auto closes that's just as annoying. I'll implement an ajax html get replace the central content instead. This will still be replaced later _but_ it's better for now.

**Comment by Chris7** [comment]
Ah I understand now. Persisting what your search results are. I'm fine with whatever you come up with, given it's a stop-gap solution we shouldn't be re-inventing too many things.

**Comment by mfitzp** [comment]
@Chris7 The various branches have all now been merged and I've moved remaining issues over to the other repository. If you can give me a :+1: that I've not forgotten something really obvious I'll perform the migration.

**Comment by Chris7** [comment]
Let's launch! :+1:

**Comment by mfitzp** [comment]
It is done... :) https://github.com/wooey/Wooey

Will leave this repository around until we've confirmed everything has moved over and is working 100% but should not be any problems.
