### ISSUE TITLE
Favourites (Scrapbook, Scripts)

### ISSUE THREAD

**Issue by mfitzp** [wooey/django-djangui#18]
In the interface update I've start on support for favouriting scripts so that logged in users can get a nice easy route from the front page. The idea would be to list them first, followed by most frequent (per user), followed by most popular. With a search on top of that.

It occurred to me it might be a nice feature to be able to favourite outputs as well - think that often when you run a script you get a few hundred files, but you just one a single figure. The idea would be that 'favouriting' that adds it to some kind of "Scrapbook" view, which just lists all the favourited outputs along with some job metadata. It becomes a neat little summary of all a user's important outputs.

It would have implications for storage (i.e. we would need to protect favourites from deletion if we clean up jobs, etc.) but worth thinking about.

I suspect this won't be done/worked out before the merge, but just a thought.

**Comment by Chris7** [comment]
Would favorites be redundant with a user's own script grouping capability? Wouldn't they naturally order them in a 'favorites' style? I guess I need to see where you end up with the interface to see what is the functionality.

I love the scrapbook idea. You can have multiple scrapbooks that entail basically your final results for a paper/presentation/whatever. for the figures you have an 'add to scrapbook' dropdown with a filter for known scrapbooks.

**Comment by mfitzp** [comment]
Can users group scripts? I thought the script grouping was for admins only.

What are the use cases you’re thinking of for the grouping? I can see how it could be useful, but wonder how much it’ll be used. The nice thing about ‘favourite’ is that it’s a single click + it’s added. Supporting user categories requires them to create categories, manage things in them etc. 

The idea I had was for a logged in user at the homepage would be a list of all favourite scripts, then popular. Non-users get the popular list only. Above this will be a search bar entry, so you can just start typing and get matching scripts. 

For some sort of discoverability I was either thinking of adding popular tag listing (between favourites<>popular) or having categories listing in the sidebar. If we keep tags admin-only then the distinction between them and categories is moot (or we can ‘mark’ top level tags, etc.)

That said, some kind of user-categorisation system would be really useful for scrapbooks. 

Here’s a thought… I guess categories could be implemented like folders with a similar sort of interface you see on mobile: drag two things on top of each other and it puts them in a folder grouped. That makes the categorisation nice and straight forward, but also allows simple favouriting (by default they end up top level, but you can group them if you like).

I’ve implemented some basic sharing for the data outputs (it will need fixing to use a secret md5 url. We can do the same thing on scrapbooks e.g. researchers can send a link to supervisors etc.

On 20 July 2015 at 18:20:12, Chris Mitchell (notifications@github.com) wrote:

Would favorites be redundant with a user's own script grouping capability? Wouldn't they naturally order them in a 'favorites' style? I guess I need to see where you end up with the interface to see what is the functionality.

I love the scrapbook idea. You can have multiple scrapbooks that entail basically your final results for a paper/presentation/whatever. for the figures you have an 'add to scrapbook' dropdown with a filter for known scrapbooks.

**Comment by Chris7** [comment]
Script groups were just so you can easily control access to a group of scripts and provide some sort of grouping from an admin stance. But it's a bit narrow in its scope, so I don't mind seeing them go.

I think favorites + tags + user tags would cover all the functionality we are looking for (combined with the interface you described with the search)

**Comment by mfitzp** [comment]
This was merged in with ede20d9

![ED209](http://vignette3.wikia.nocookie.net/robocop/images/e/ef/Ed209.jpg/revision/latest?cb=20100116202642)
