### ISSUE TITLE
Setup.py authors

### ISSUE THREAD

**Issue by Chris7** [wooey/django-djangui#21]
I found this for setting up multiple authors in setup.py:

http://bugs.python.org/msg93286

I'm not sure which email you'd like to use @mfitzp, I'm ok with my gmail being in there. Can you update the authors field in the style of that link (or let me know which email you'd want attached?)

**Comment by mfitzp** [comment]
My gmail one is fine - martin.fitzpatrick@gmail.com - it's already all over
the internet (and in the commit logs) so it won't do any harm.

I already get emails from a cricket club in Australia, a golf club in
Florida, a magazine about farming vehicles and I'm on a Fitzpatrick-family
mailing list somewhere in New England (they just had a new grandson). It's
a pretty exciting double life.

**Comment by Chris7** [comment]
Ha, I read somewhere about gmail's decision to ignore punctuation (periods and maybe some more) in email addresses causing grief such as that. Maybe you are a victim of it.
