### ISSUE TITLE
Script view in new window

### ISSUE THREAD

**Issue by Chris7** [wooey/django-djangui#23]
I like keeping the script view in the same place where the user can select scripts -- so they can explore without having to open new tabs/go back and forth. 

I think populating the blue wooey window bar would be a good area for this. The script can occupy that (with a scrollbar if needed) and expand its area slightly.

Also, this is completely ignoring the discussion on making a more power-dashboard style interface. What is your stance on the completeness of the interface @mfitzp? What are your thoughts on the dashboard (with a left bar that is very interactive)?

**Comment by mfitzp** [comment]
Yep I would like to have it be a bit more interactive 'explorable' for discovery... as it is I can imagine with >50 odd scripts it would become very much "this?" "oh, no" _back_ "this?" "oh, no" _back_ "this?". 

My goal is to transition the UI to something far more dynamic as a whole (AngularJS?) in the longer term but I wasn't clued up enough on that to make prototyping easy :)

One idea I did have was for opening a tool to split the screen with the tool list remaining on the left + the script config appearing on the right (expandable to whole page). Submitting a job could move the submission view to the left, and the output to the right (again expandable) ...in effect an across-the-page accordian thing. I'll need to play with that to see if it's useable in practise.

A (simpler) option would be to keep the result of the front page search/etc. available in a sidebar panel to the left. There was a plan to add a sidebar anyway, it just got forgotten about! This way the user can just work there way through the scripts there - adding a search box at the top would make it nicer and interactive. They could just keep looking for tools that way.... this is easy enough to implement I could do it before "The Merge" if you like?

(I've actually removed the blue area for logged in users in one of the latest commits (to make more space for other dashboardy things) but that can of course come back.)

**Comment by Chris7** [comment]
I really think the sidebar is the way to go for this. It's easily extensible, intuitive to everyone, and works very well for making responsive interfaces. What sort of bar were you thinking of?

I think the simplistic design of the home screen is a good idea right now -- it isn't intimidating and its straight forward. The part that could use some smoothing out is navigating between options in a manner that isn't repetitive and facilitates exploration. What appeals most to me is a left sidebar that can pop out that provides the user with a means to navigate nearly anywhere.

**Comment by mfitzp** [comment]
One idea I had for the sidebar would be something like a 'portable dashboard' so containing updates of things happening elsewhere. This would tie into a kind of 'system notifications' thing where events — script submitted, job complete, etc. would create back-end events that could be presented to the user either on the sidebar, or as alerts over the main view when the sidebar is closed.

At the top of this there would be a search bar which would allow searching for anything - scripts, tasks, jobs, etc. that would be shown in the sidebar. But I think some kind of directory-like view would be good for when not searching.... so maybe (together with the above) we might need two sidebars ;)

**Comment by mfitzp** [comment]
Started work on the sidebar — see #28

**Comment by mfitzp** [comment]
Merged.
