### ISSUE TITLE
Anonymous users cannot see completed jobs

### ISSUE THREAD

**Issue by Chris7** [wooey/django-djangui#24]
I don't see a way for an anonymous user to look at their job output.

**Comment by mfitzp** [comment]
Good catch. You can see the output if you have the URL but there is nowhere in the interface to get there. I could add a separate "Public" (?) jobs drop down visible when not-logged in - and the additional view for the full list?

**Comment by mfitzp** [comment]
Just occurred to me that an easier way to fix is just show anon jobs in the "Results" dropdown for anonymous users and the same for the /results/user link. Only change then is to include "Results" in the visible set for anonymous users.

**Comment by Chris7** [comment]
Yeah, I think that's a good approach for it.

**Comment by mfitzp** [comment]
Fixed by ff17b79cb2962a7b1b9625d7603a9c660e009094  ...turned out it was already working on the backend - unhid the dropdown and _done_ :)
