### ISSUE TITLE
General Interface Improvements

### ISSUE THREAD

**Issue by Chris7** [wooey/django-djangui#25]
I figured a general issue thread would be better than a bunch of individual issues, so I'm just going to put things as I see them here.

Anonymous users can click the favorite but cannot favorite. A mouseover telling them they cannot favorite without being logged in can be useful.

In the script submission view, I think the job metadata should be first because it is required. I also think it's a bit verbose having to scroll through every group to get to the bottom. I liked keeping groups as tabs to allow users to ignore options they don't plan on selecting.

**Comment by mfitzp** [comment]
I was wondering about the metadata — I find it kind of annoying having to fill that in but it _is_ required to be able to tell the jobs apart. What do you think about auto-filling it in some way? Something like script-user-timestap for the title (is the description required?)

:+1:  on the tabs for the groups actually...  I think I removed them because it was hard to make it look "nice" with the panels also. But they're generally useful to have in the UI so I'll work out the CSS.

Good catch on the anonymous users — do you think it makes sense just to hide favoriting? We can do this really easily with CSS by applying a not-logged-in class to body, using requires-login on elements that need it and `.not-logged-in .requires-login { display: none; }`

**Comment by mfitzp** [comment]
What do you think of this?

![screen shot 2015-08-06 at 21 42 36](https://cloud.githubusercontent.com/assets/126239/9121678/1f4fe2f2-3c84-11e5-9dd1-6f8efe43de84.png)
![screen shot 2015-08-06 at 21 42 39](https://cloud.githubusercontent.com/assets/126239/9121679/210e329c-3c84-11e5-89d6-4c898235c4e0.png)

**Comment by Chris7** [comment]
I think that looks great!

For the metadata, I had the exact same thought -- most times I know I should fill it out, but sometimes you just want to practice bad habits :). I was thinking along the same lines -- just script-name-# (the pk maybe)? I think a timestamp can be unwieldly because it's just so many characters, but that's just my opinion. If you'd prefer that, I'm fine with a timestamp. But +1 on autopopulating metadata.

**Comment by Chris7** [comment]
I think the CSS approach is good too, and makes our template rendering simpler.

**Comment by mfitzp** [comment]
The latest commit should fix the issues in this bug but I'll leave it open for new ones!

**Comment by Chris7** [comment]
script_view extends base.html instead of home.html. This causes the multi-input not to operate since it is in home. Did you mean to extend base instead of home?

**Comment by mfitzp** [comment]
Yep all the templates now extend `base.html` — the base template contains the page layout/structure (header bars, etc.) while `home.html` has the homepage view region only.

Most of the JS should be in `base.html` now — the only thing left would be the search, but then that will move once the sidebar search is implemented. So... all of it I guess! We should probably consider moving this to static files later.

Can you do that and make the commit? I don't have a multi-input script on hand test it with here.

**Comment by mfitzp** [comment]
Speaking of which... should we include a set of demo scripts in the repo somewhere? `/examples` maybe? Would be nice for getting people up and running quickly.

There are a few in the flask-wooey repo so we can copy those over too.

**Comment by Chris7** [comment]
I think that's good. I have a few test scripts that do simple/dumb things as well in the test scripts directory. 

To summarize this, I think what's left is:
1) default metadata -- I think a placeholder of the default and using that if they fail to fill it out is a good approach, since it doesn't require people to delete/modify whatever is already there.
2) CSS for anonymous users

**Comment by mfitzp** [comment]
The anonymous CSS _should_ be done. Can you still see the favoriting things somewhere?

I'll do the default metadata now :)

**Comment by Chris7** [comment]
Oh great, I didn't recall the anonymous bit being done. So only 1 thing left :)

**Comment by mfitzp** [comment]
Both done now :+1:  in #28
