### ISSUE TITLE
Script Markup

### ISSUE THREAD

**Issue by Chris7** [wooey/django-djangui#5]
An interface to edit scripts and provide more detailed, customized documentation.

**Comment by mfitzp** [comment]
By "customized documentation" do you mean instructions, references etc? This would be really nice to have (I'll leave space for it in the UI). In the flask-wooey I read this in from a markdown file but with everything in the database it makes more sense to have a field there to support it, e.g. `about` or `long_description` or `help`?

Do you think it's worth supporting auto-loading markdown files (matching .md file to .py file, or README.md in the same folder) when importing?

**Comment by mfitzp** [comment]
Moving to the Wooey repo.
