### ISSUE TITLE
Dashboard-style layout

### ISSUE THREAD

**Issue by Chris7** [wooey/django-djangui#6]
Move the frontend to a style like these:
http://marketblog.envato.com/resources/bootstrap-admin-templates/

**Comment by Chris7** [comment]
Base Features:
Share jobs with other users
Share files with other users

Future Enhancements:
Job file output management via something like:

File manager:
http://django-media-tree.readthedocs.org/en/latest/extending.html

**Comment by mfitzp** [comment]
The work on the update interface is in full swing in the `interface-updates` [branch](https://github.com/wooey/django-djangui/tree/interface-updates). At present it's looking much like flask-wooey and the navigation is broken but this should be resolved soon.

Once all the base views are complete I'll start work on building the dashboard interface.

**Comment by Chris7** [comment]
Sounds good, want to create a PR so we can discuss the branch and comment on code changes in there/etc?

**Comment by mfitzp** [comment]
Just tried, but it's creating the pull-request against your repo at django-djangui. Is it possible to create a PR within the same repo (branch to master)?

I could always fork this to a private repo and open a PR from there.

**Comment by Chris7** [comment]
If you change the base repo to here it'll make it against this codebase.

**Comment by mfitzp** [comment]
Ah, kind of obvious now you mention it. PR open here https://github.com/wooey/django-djangui/pull/16

**Comment by mfitzp** [comment]
PR #16 merged as ede20d9 although it doesn't include all the features listed here. Should we move this to a new issue on the other repo?

**Comment by Chris7** [comment]
I think a new issue is warranted, we can work on these features there.

**Comment by mfitzp** [comment]
Moved to https://github.com/wooey/Wooey/issues/21
